---
- name: Playbook
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: "Install pip dependencies"
      pip:
        name: 
          - pyowm
          - geopy
        executable: pip3